import random
import pycowsay

FORTUNES = [
    "A closed mouth catches no flies.",
    "A journey of a thousand miles begins with a single step.",
    "All that glitters is not gold.",
    "An apple a day keeps the doctor away.",
    "Beware of the man who has nothing to lose.",
    "Don't count your chickens before they hatch.",
    "Every cloud has a silver lining.",
    "Fortune favors the bold.",
    "Haste makes waste.",
    "If you want something done right, do it yourself.",
    "Knowledge is power.",
    "Laughter is the best medicine.",
    "Measure twice, cut once.",
    "Necessity is the mother of invention.",
    "No gain without pain.",
    "Nothing ventured, nothing gained.",
    "Practice what you preach.",
    "Rome wasn't built in a day.",
    "Still waters run deep.",
    "The early bird catches the worm.",
    "The pen is mightier than the sword.",
    "There's no place like home.",
    "Time flies when you're having fun.",
    "To err is human; to forgive divine.",
    "Well begun is half done.",
    "When in Rome, do as the Romans do.",
    "You can't judge a book by its cover.",
    "You reap what you sow.",
    "A rolling stone gathers no moss.",
    "Actions speak louder than words.",
    "Beauty is in the eye of the beholder.",
    "Cleanliness is next to godliness.",
    "Curiosity killed the cat.",
    "Discretion is the better part of valor.",
    "East or west, home is best.",
    "Every man has his price.",
    "Good things come to those who wait.",
    "Honesty is the best policy.",
    "If at first you don't succeed, try, try again.",
    "Ignorance is bliss.",
    "It takes two to tango.",
    "Let sleeping dogs lie.",
    "Look before you leap.",
    "Many hands make light work.",
    "Out of sight, out of mind.",
    "Patience is a virtue.",
    "Pride comes before a fall.",
    "Silence is golden.",
    "The grass is always greener on the other side.",
    "The more things change, the more they stay the same.",
    "There's no smoke without fire.",
    "Too many cooks spoil the broth.",
    "Variety is the spice of life.",
    "What goes around comes around.",
    "You can lead a horse to water, but you can't make it drink.",
    "Your future is as bright as your faith.",
    "A change is as good as a rest.",
    "Birds of a feather flock together.",
    "Charity begins at home.",
    "Desperate times call for desperate measures.",
    "Don't bite the hand that feeds you.",
    "Don't put all your eggs in one basket.",
    "Every dog has its day.",
    "Fools rush in where angels fear to tread.",
    "Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.",
    "Half a loaf is better than none.",
    "If the shoe fits, wear it.",
    "It's no use crying over spilled milk.",
    "Keep your friends close and your enemies closer.",
    "Love is blind.",
    "Money doesn't grow on trees.",
    "Old habits die hard.",
    "One man's trash is another man's treasure.",
    "People who live in glass houses shouldn't throw stones.",
    "Seeing is believing.",
    "The best things in life are free.",
    "The devil is in the details.",
    "The squeaky wheel gets the grease.",
    "There's more than one way to skin a cat.",
    "Two heads are better than one.",
    "When it rains, it pours.",
    "You can't have your cake and eat it too.",
    "A friend in need is a friend indeed.",
    "All good things must come to an end.",
    "Better late than never.",
    "Blood is thicker than water.",
    "Don't make a mountain out of a molehill.",
    "Easy come, easy go.",
    "Forewarned is forearmed.",
    "Great minds think alike.",
    "History repeats itself.",
    "If you can't beat 'em, join 'em.",
    "It's better to be safe than sorry.",
    "Let bygones be bygones.",
    "Murphy's law: anything that can go wrong will go wrong.",
    "Nobody is perfect.",
    "Once bitten, twice shy.",
    "Practice makes perfect.",
    "The end justifies the means.",
    "The truth shall set you free.",
    "Waste not, want not.",
    "You are the master of your own destiny.",
]

TECH_FORTUNES = [
    "There are only two hard things in computer science: cache invalidation and naming things.",
    "It works on my machine.",
    "Have you tried turning it off and on again?",
    "Any sufficiently advanced technology is indistinguishable from magic.",
    "The best error message is the one that never appears.",
    "A bug is never just a mistake. It represents something bigger.",
    "Programs must be written for people to read, and only incidentally for machines to execute.",
    "Simplicity is prerequisite for reliability.",
    "Before software can be reusable it first has to be usable.",
    "The most dangerous phrase in the language is 'we've always done it this way.'",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
    "First, solve the problem. Then, write the code.",
    "Code is like humor. When you have to explain it, it's bad.",
    "Make it work, make it right, make it fast.",
    "Deleted code is debugged code.",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
    "There are two ways to write error-free programs; only the third one works.",
    "A good programmer is someone who always looks both ways before crossing a one-way street.",
    "The code you write makes you a programmer. The code you delete makes you a good one.",
    "Don't comment bad code -- rewrite it.",
]

class Extension:
    def __init__(self, config):
        self.config = config
        try:
            cow = pycowsay.get_output('Fortune Cookie loaded')
            print(f'[FortuneCookie] {cow.split(chr(10))[0]}...')
        except Exception:
            print('[FortuneCookie] pycowsay loaded')

    def get_fortune(self):
        all_fortunes = FORTUNES + TECH_FORTUNES
        return {"value": random.choice(all_fortunes)}
